import type { BotSettingsUpdateInput, BotSettingsView } from '$lib/types/bot.js';

const DEFAULT_UPDATED_AT = new Date(0).toISOString();

export const BOT_SETTINGS_DEFAULTS: BotSettingsUpdateInput = {
	network: 'mainnet',
	rpc_url: 'https://fullnode.mainnet.sui.io:443',
	experimental_deeptrade_limit_ptb: false,
	deeptrade_orderbook_api_base: 'https://api.deeptrade.space/api',
	pool_key: 'SUI_USDC',
	account_a_label: 'Account A (Long)',
	account_b_label: 'Account B (Short)',
	private_key_A: '',
	private_key_B: '',
	notional_size_usd: 4,
	min_hold_seconds: 150,
	max_hold_seconds: 210,
	max_cycles: 3,
	slippage_tolerance: 0.005,
	random_size_bps: 200,
	min_order_delay_ms: 600,
	max_order_delay_ms: 1400,
	open_order_execution_mode: 'limit',
	close_order_execution_mode: 'limit',
	auto_swap_enabled: true,
	auto_swap_buffer_bps: 500,
	min_gas_reserve_sui: 0.15,
	order_poll_interval_ms: 2500,
	maker_reprice_seconds: 30,
	force_market_close_seconds: 20,
	account_a_margin_manager_id: undefined,
	account_b_margin_manager_id: undefined,
	account_a_borrow_quote_factor: 2,
	account_b_borrow_base_factor: 2,
	notional_auto_reduce_floor_pct: 100
};

export const createDefaultSettingsView = (): BotSettingsView => ({
	network: BOT_SETTINGS_DEFAULTS.network,
	rpc_url: BOT_SETTINGS_DEFAULTS.rpc_url,
	experimental_deeptrade_limit_ptb: BOT_SETTINGS_DEFAULTS.experimental_deeptrade_limit_ptb,
	deeptrade_orderbook_api_base: BOT_SETTINGS_DEFAULTS.deeptrade_orderbook_api_base,
	pool_key: BOT_SETTINGS_DEFAULTS.pool_key,
	account_a_label: BOT_SETTINGS_DEFAULTS.account_a_label,
	account_b_label: BOT_SETTINGS_DEFAULTS.account_b_label,
	notional_size_usd: BOT_SETTINGS_DEFAULTS.notional_size_usd,
	min_hold_seconds: BOT_SETTINGS_DEFAULTS.min_hold_seconds,
	max_hold_seconds: BOT_SETTINGS_DEFAULTS.max_hold_seconds,
	max_cycles: BOT_SETTINGS_DEFAULTS.max_cycles,
	slippage_tolerance: BOT_SETTINGS_DEFAULTS.slippage_tolerance,
	random_size_bps: BOT_SETTINGS_DEFAULTS.random_size_bps,
	min_order_delay_ms: BOT_SETTINGS_DEFAULTS.min_order_delay_ms,
	max_order_delay_ms: BOT_SETTINGS_DEFAULTS.max_order_delay_ms,
	open_order_execution_mode: BOT_SETTINGS_DEFAULTS.open_order_execution_mode,
	close_order_execution_mode: BOT_SETTINGS_DEFAULTS.close_order_execution_mode,
	auto_swap_enabled: BOT_SETTINGS_DEFAULTS.auto_swap_enabled,
	auto_swap_buffer_bps: BOT_SETTINGS_DEFAULTS.auto_swap_buffer_bps,
	min_gas_reserve_sui: BOT_SETTINGS_DEFAULTS.min_gas_reserve_sui,
	order_poll_interval_ms: BOT_SETTINGS_DEFAULTS.order_poll_interval_ms,
	maker_reprice_seconds: BOT_SETTINGS_DEFAULTS.maker_reprice_seconds,
	force_market_close_seconds: BOT_SETTINGS_DEFAULTS.force_market_close_seconds,
	account_a_margin_manager_id: undefined,
	account_b_margin_manager_id: undefined,
	account_a_borrow_quote_factor: BOT_SETTINGS_DEFAULTS.account_a_borrow_quote_factor,
	account_b_borrow_base_factor: BOT_SETTINGS_DEFAULTS.account_b_borrow_base_factor,
	notional_auto_reduce_floor_pct: BOT_SETTINGS_DEFAULTS.notional_auto_reduce_floor_pct,
	has_private_key_a: false,
	has_private_key_b: false,
	updated_at: DEFAULT_UPDATED_AT
});
